config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit:
      branch: 487-improve-searchkit-sqa-rating
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-thistle-horse.sh
        container: qc.acc_ready-cinnabar-crab
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-yellow-chicken.sh
        container: qc.doc_snazzy-periwinkle-chow
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ecru-crocodile.sh
        container: qc.doc_slimy-firebrick-lobster
      bitbucket.org/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-aquamarine-cassowary.sh
        container: qc.doc_smelly-ruby-mau
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-flax-abyssinian.sh
        container: qc.lic_cozy-auburn-abyssinian
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-ruby-squid.sh
        container: qc.met_flimsy-cobalt-duck
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-maroon-gorilla.sh
        container: qc.sty_stinky-asparagus-insect
      bitbucket.org/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-jade-akbash.sh
        container: qc.sty_frumpy-burgundy-lizard
      bitbucket.org/cessda/cessda.cdc.searchkit stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-heliotrope-woodlouse.sh
        container: qc.sty_blurry-salmon-quetzal
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-russet-gecko.sh
        container: qc.ver_smelly-harlequin-stoat
timeout: 1800
