config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit:
      branch: 487-improve-searchkit-sqa-rating
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lilac-beetle.sh
        container: qc.acc_chummy-plum-dodo
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-blue-mole.sh
        container: qc.doc_homely-sepia-dugong
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-blue-ladybird.sh
        container: qc.doc_surly-copper-kakapo
      bitbucket.org/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mauve-moose.sh
        container: qc.doc_gamy-indigo-blue
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-eggplant-quokka.sh
        container: qc.lic_stuffy-harlequin-leopard
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-magenta-fousek.sh
        container: qc.met_freaky-mauve-eel
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-platinum-reindeer.sh
        container: qc.sty_pasty-sangria-whale
      bitbucket.org/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-eggplant-worm.sh
        container: qc.sty_hazy-puce-kudu
      bitbucket.org/cessda/cessda.cdc.searchkit stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-wisteria-giraffe.sh
        container: qc.sty_seedy-tan-antelope
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-orchid-markhor.sh
        container: qc.ver_thirsty-flax-chin
timeout: 1800
