config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit:
      branch: 487-improve-searchkit-sqa-rating
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-magenta-pig.sh
        container: qc.acc_craggy-dandelion-frise
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-fuchsia-paradise.sh
        container: qc.doc_bluesy-flax-angora
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-tomato-lynx.sh
        container: qc.doc_surly-blue-catfish
      bitbucket.org/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-emerald-cockroach.sh
        container: qc.doc_scanty-peach-chinchilla
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-bronze-barracuda.sh
        container: qc.lic_paltry-tan-kakapo
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-burgundy-wrasse.sh
        container: qc.met_cozy-cream-rottweiler
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-violet-otter.sh
        container: qc.sty_paltry-puce-coati
      bitbucket.org/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-indigo-newfoundland.sh
        container: qc.sty_chummy-magenta-clam
      bitbucket.org/cessda/cessda.cdc.searchkit stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-indigo-ibis.sh
        container: qc.sty_ugly-flax-monkey
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-gamboge-labradoodle.sh
        container: qc.ver_clammy-sangria-quetzal
timeout: 1800
