config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit:
      branch: 487-improve-searchkit-sqa-rating
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-salmon-chicken.sh
        container: qc.acc_slimy-burgundy-zorse
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-wheat-numbat.sh
        container: qc.doc_smelly-white-emu
      bitbucket.org/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ivory-kakapo.sh
        container: qc.doc_muggy-chestnut-wallaby
      bitbucket.org/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-asparagus-hornet.sh
        container: qc.doc_cranky-silver-caterpillar
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-persimmon-camel.sh
        container: qc.lic_goopy-ecru-goat
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-vermilion-mayfly.sh
        container: qc.met_cloudy-bronze-ostrich
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cerise-bobcat.sh
        container: qc.sty_muzzy-thistle-hare
      bitbucket.org/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-copper-eel.sh
        container: qc.sty_dorky-cinnabar-tang
      bitbucket.org/cessda/cessda.cdc.searchkit stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-rust-dolphin.sh
        container: qc.sty_clammy-pumpkin-abyssinian
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-magenta-rabbit.sh
        container: qc.ver_stinky-tangerine-loon
timeout: 1800
